allowBuilds:
  esbuild: true
patchedDependencies:
  '@arethetypeswrong/core@0.18.2': patches/@arethetypeswrong__core@0.18.2.patch

peerDependencyRules:
  allowedVersions:
    # This can go once https://github.com/release-it/keep-a-changelog/pull/42 is merged
    "@release-it/keep-a-changelog>release-it": "19"
