// flow-typed signature: 490c19ce9a2e0c4171bc62ba6c88d9e1
// flow-typed version: <<STUB>>/import-sort-cli_v^4.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-sort-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-sort-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-sort-cli/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-sort-cli/lib/index.js' {
  declare module.exports: $Exports<'import-sort-cli/lib/index'>;
}
