name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
            # From https://github.com/nodejs/Release
            "22.x", # EoL by 2027-04-30
            "24.x", # EoL by 2028-04-30
            "26.x", # EoL by 2029-04-30
            "latest",
          ]

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check TypeScript
        run: pnpm exec tsc

      - name: Run tests
        run: pnpm run test
        env:
          CI: true

      - name: Run type-level tests
        run: pnpm run test:types
        env:
          CI: true

      - name: Run linters
        run: pnpm run lint

      - name: Run NPM package lints
        run: |
          pnpm run build
          pnpm run lint:package
        # @arethetypeswrong/cli requires Node 18+, it seems?
        # See https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/52
        if: ${{ matrix.node-version == '18.x' || matrix.node-version == 'latest' }}
